//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_order()
        {
            this.tb_orderdetail = new HashSet<tb_orderdetail>();
        }
    
        public int o_id { get; set; }
        public int o_cus_id { get; set; }
        public System.DateTime o_date { get; set; }
        public string o_pay { get; set; }
        public string o_shipadd { get; set; }
        public string o_folder { get; set; }
        public int o_pr_id { get; set; }
        public string o_recip { get; set; }
        public string o_recip_phone { get; set; }
        public System.DateTime o_deli_date { get; set; }
        public int o_s_id { get; set; }
        public int o_dt_id { get; set; }
        public string o_status { get; set; }
    
        public virtual tb_customer tb_customer { get; set; }
        public virtual tb_deliverytime tb_deliverytime { get; set; }
        public virtual tb_printsize tb_printsize { get; set; }
        public virtual tb_shippingcategory tb_shippingcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderdetail> tb_orderdetail { get; set; }
    }
}
