//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_image()
        {
            this.tb_orderdetail = new HashSet<tb_orderdetail>();
        }
    
        public int img_id { get; set; }
        public string img_size { get; set; }
        public int img_copies { get; set; }
        public string img_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderdetail> tb_orderdetail { get; set; }
    }
}
