//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_orderdetail
    {
        public int orderdetail_id { get; set; }
        public int orderdetail_o_id { get; set; }
        public int orderdetail_img_id { get; set; }
    
        public virtual tb_image tb_image { get; set; }
        public virtual tb_order tb_order { get; set; }
    }
}
